// FILE: server/controllers/scheduleController.js
const User = require('../models/User');
const DailySchedule = require('../models/DailySchedule');
const { getTodaySchedule, updateTaskStatus, getCompletionStats } = require('../services/scheduleService');

// @route GET /api/schedule/today
const getToday = async (req, res, next) => {
    try {
        const elder = await User.findById(req.user._id);
        const schedule = await getTodaySchedule(elder);
        const stats = getCompletionStats(schedule);
        res.json({ success: true, schedule, stats });
    } catch (err) {
        next(err);
    }
};

// @route POST /api/schedule/generate  (force-regenerate)
const generateSchedule = async (req, res, next) => {
    try {
        const elder = await User.findById(req.user._id);
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        // Delete existing schedule for today if regenerating
        await DailySchedule.deleteOne({ elderId: elder._id, date: today });

        const schedule = await getTodaySchedule(elder);
        const stats = getCompletionStats(schedule);

        res.json({ success: true, schedule, stats, message: 'Schedule regenerated by AI' });
    } catch (err) {
        next(err);
    }
};

// @route PUT /api/schedule/task/:taskId
const updateTask = async (req, res, next) => {
    try {
        const { taskId } = req.params;
        const { status, refusalReason, notes } = req.body;

        const validStatuses = ['pending', 'done', 'skipped', 'refused'];
        if (status && !validStatuses.includes(status)) {
            return res.status(400).json({ success: false, message: 'Invalid status' });
        }

        const { schedule, task } = await updateTaskStatus(req.user._id, taskId, { status, refusalReason, notes });
        const stats = getCompletionStats(schedule);

        // Emit socket event to guardian if linked
        const elder = await User.findById(req.user._id);
        if (elder.guardianId && status === 'done') {
            req.io.to(elder.guardianId.toString()).emit('task_completed', {
                elderId: elder._id,
                taskId,
                taskType: task.type,
                taskTitle: task.title,
                timestamp: new Date()
            });
        }

        res.json({ success: true, task, stats });
    } catch (err) {
        next(err);
    }
};

// @route GET /api/schedule/history  (guardian view)
const getHistory = async (req, res, next) => {
    try {
        const { elderId } = req.params;
        const targetId = elderId || req.user._id;

        const schedules = await DailySchedule.find({ elderId: targetId })
            .sort({ date: -1 })
            .limit(30);

        res.json({ success: true, schedules });
    } catch (err) {
        next(err);
    }
};

module.exports = { getToday, generateSchedule, updateTask, getHistory };